### ISSUE TITLE
size display popup emoji wrong when update version 0.7.0 

### ISSUE THREAD

**Issue by binhhoit** [vanniktech/Emoji#487] opened 2021-01-28 10:19 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.7.0
- Affected devices: all device
- Affected versions: : 8.0
the new version upgrades very bad dialog. I don't change anything in the source code and update 0.6.0 -> 0.7.0 I have a bug show full-screen dialog emoji. this bug does not have when downgrading 0.6.0. thanks, the team I hope it fixes the new version continues.

![device-2021-01-28-135423](https://user-images.githubusercontent.com/29090540/106123374-6b648e80-618c-11eb-95f5-00079e929c14.png)

----------------------------------------------------------------------

**Comment by vanniktech** [comment] 2021-04-20 06:49
Dupe of #474

**Closed by vanniktech** 2021-04-20 06:49 UTC
