### ISSUE TITLE
Emoji Layout poping above keyboard layout

### ISSUE THREAD

**Issue by emondd4** [vanniktech/Emoji#490] opened 2021-03-31 06:54 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.7.0
- Affected devices: Xiaomi Note 7
- Affected versions: Android 10
- Though I am using "android:windowSoftInputMode="stateAlwaysHidden|adjustResize" in my menifest
- and even using " android:fitsSystemWindows="true" " in my root view

Screenshot(s) showing the issue and reprodution steps are appreciated.

![Screenshot_20210331-123600](https://user-images.githubusercontent.com/41892885/113102492-ef380700-921f-11eb-9fbd-08f0cef6584e.png)

----------------------------------------------------------------------

**Comment by akteruzzaman816** [comment] 2021-04-01 06:05
any solution to this problem?

**Comment by vanniktech** [comment] 2021-04-20 06:47
Dupe of #472

**Closed by vanniktech** 2021-04-20 06:47 UTC
