### ISSUE TITLE
Can't show keybord

### ISSUE THREAD

**Issue by lukitnev** [vanniktech/Emoji#58] opened 2016-09-06 19:44 UTC
Hello. Thanks for so good lib.
Help me to resolve this problem (as here: https://github.com/vanniktech/Emoji/issues/28 ), please:
Board with smiles opening good, but I want to switch smiles board to keybord by second tap to button. 
So, smiles board opened, I tap on button, where this code:

> if (main.globals_.emojiPopup.isShowing()){
>                     //закрыть эмоции
>                     //main.globals_.emojiPopup.dismiss();
>                     //показать клавиатуру
>                     InputMethodManager imm = (InputMethodManager)  getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
>                     imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
>                 }else{
>                     //открыть эмоции
>                     main.globals_.emojiPopup.toggle();
>                 }

and I see momental keyboard blink, closing keyboard and smiles board was closed.

If I delete the code for showing keyboard and uncomment main.globals_.emojiPopup.dismiss(); , I will see good changing from smiles to keboard and back. BUT, when I close keyboard or smiles by pressing "back" and trying to show smiles by button, I will see the bug as on screen from issue #28. What me do? How to set rootView again?
Sorry for my Russian English.

**Comment by lukitnev** [comment] 2016-09-06 20:06
I solve this with next hack:

>         //Слушатель: Открыть панель выбора смайлов
        showEmojiBoard.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                main.helpFuncs.fastVibrate(getContext());
                if (main.globals_.emojiPopup.isShowing()){
                    //закрыть эмоции
                    main.globals_.emojiPopup.dismiss();
                }else{
                    //закрыть клавиатуру
                    InputMethodManager imm = (InputMethodManager)getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
                    imm.hideSoftInputFromWindow(emojiEditText.getWindowToken(), 0);
                    //открыть эмоции
                    main.globals_.emojiPopup.toggle();
                }
            }
        });

**Comment by vanniktech** [comment] 2016-09-07 07:46
Have you looked at the sample and does that work?

**Comment by lukitnev** [comment] 2016-09-07 11:14
Yes, not only look. I use example, but example work good only with code in my onClickListener. Without this, example can only show smiles board.

**Comment by vanniktech** [comment] 2016-09-07 11:26
Which device are you using and does it have a custom keyboard?

**Comment by lukitnev** [comment] 2016-09-07 11:29
Sony Ericsson Xperia mini sk17i (android 4.0.4) without custom keyboard and Samsung Galaxy S3 without custom keyboard

**Comment by vanniktech** [comment] 2016-09-07 11:45
I do know that there seems to be something mixed up in some cases and on some devices I just can't never reproduce it hence I don't know what's going on.

Adding that logic may work for that particular device however it can break many more devices.

**Comment by vanniktech** [comment] 2016-11-19 13:40
I'll close this as this should be fixed with `0.4.0-SNAPSHOT`. If it isn't please create / reopen the issue. I'll cut a release soon.

**Closed by vanniktech** 2016-11-19 13:40 UTC
Labels: bug, Needs Info
