### ISSUE TITLE
The full screen is abnormal

### ISSUE THREAD

**Issue by hello-brothers** [vanniktech/Emoji#572] opened 2022-04-11 07:10 UTC
when the Application or activity style is fullScreen (android:theme="@android:style/Theme.NoTitleBar.Fullscreen") 
or set window.setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN)  in activity, the emoji pop is abnormal
version:0.9.0

![011](https://user-images.githubusercontent.com/23499816/162683612-e65a0aa2-7c14-4c25-9b82-97ccf46ffaeb.png)

**Comment by vanniktech** [comment] 2022-04-11 07:38
Yeah, we've had a few reports of that. I was never able to reproduce. Do you mind trying out our sample app and see if you can come up with a fix?

**Comment by mahibi** [comment] 2022-04-25 10:06
duplicate of: https://github.com/vanniktech/Emoji/issues/474

**Closed** 2022-04-25 11:05 UTC
Labels: needs info, pr welcome
