### ISSUE TITLE
Problem showing emmoji 

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [vanniktech/Emoji#43] opened 2016-07-28 12:55 UTC
using com.vanniktech:emoji:0.3.0
when open this emoji it show both emoji and keyboard pls help
![13883907_1031409340246997_1400022487_n](https://cloud.githubusercontent.com/assets/10194731/17213119/9062f788-54f0-11e6-9e03-d6aed9ddc673.png)

**Comment by vanniktech** [comment] 2016-07-28 13:13
Dupe of #20. I wasn't able to reproduce this which device do you have?

**Comment by sunil-singh-chaudhary** [comment] 2016-07-28 15:47
Moto g3

**Comment by vanniktech** [comment] 2016-07-28 15:58
Alright I don't have that device at hand hence I can't try to reproduce it. So feel free to see whether you can figure out the issue.

**Comment by Max01010101010101** [comment] 2016-07-30 02:11
O.O        -_-

**Comment by vanniktech** [comment] 2016-11-19 13:44
Can you try the latest `0.4.0-SNAPSHOT` version? And if this issue still exists, open a new issue.

**Closed by vanniktech** 2016-11-19 13:44 UTC
Labels: bug, duplicate, question
