### ISSUE TITLE
Emoji Popup Issue

### ISSUE THREAD

**Issue by nileshkansal** [vanniktech/Emoji#308] opened 2018-10-03 08:37 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: ios-emoji 0.5.1 
- Affected devices: OnePlus 6
- Affected versions: Android Pie sdk version 28

Emoji Popup not covering Keyboard completely. Please check screenshot.

![screenshot_20181003-135604](https://user-images.githubusercontent.com/38293984/46399456-6b1b6c00-c715-11e8-8bdf-00dee37da51b.jpg)
![screenshot_20181003-140011](https://user-images.githubusercontent.com/38293984/46399458-6b1b6c00-c715-11e8-8721-069ebb8c44a4.jpg)

 

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment] 2018-10-03 09:55
Dupe of #191

**Closed by vanniktech** 2018-10-03 09:55 UTC
