### ISSUE TITLE
Emoji Popup does not overlay the whole keyboard

### ISSUE THREAD

**Issue by denjoo** [vanniktech/Emoji#986] opened 2023-05-19 11:28 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:  0.16.0
- Affected devices: Samsung S23 Ultra
- Affected versions: Android 13

Screenshot(s) showing the issue and reprodution steps are appreciated.

The emoji does not overlay the keyboard in the background. The popup covers too much from the top and too little from the bottom (check attached screenshot).

Thx for support.

Best regards
denjoo

----------------------------------------------------------------------
![IMG-SHARE_20230517_085124](https://github.com/vanniktech/Emoji/assets/20623299/9493a467-e947-4dee-9415-53f2225020a2)

**Comment by vanniktech** [comment] 2023-06-27 11:48
Related to #538 and hence closing.

**Comment by vanniktech** [comment] 2023-06-27 11:48
@denjoo by the way, PRs are more than welcome since I can't reproduce this with my phone.

**Closed by vanniktech** 2023-06-27 11:48 UTC
