### ISSUE TITLE
Emoji keyboard isn't shown

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#323] opened 2019-01-12 09:30 UTC
- Version of the library: 0.5.1
- Affected devices: All
- Affected versions: All

----------------------------------------------------------------------
When using extracted UI for edittext in horizontal mode, the emoji keyboard is not shown if EditText is NOT in focus. If it's in focus, then the edittext is extracted and covers the whole screen. (it's fine to have NO emoji keyboard in this case btw).

**Comment by vanniktech** [comment] 2019-01-12 10:32
Dupe of #314

**Closed by vanniktech** 2019-01-12 10:32 UTC

**Comment by mario** [comment] 2019-01-12 12:16
Ah, sorry about that - I was sure that I looked through all the issues. Now that I know you're active, I'll make a fix and submit a PR.
