### ISSUE TITLE
Emoji prompt showing above softkeyboard and malfunction in landscape mode

### ISSUE THREAD

**Issue by ismummy** [vanniktech/Emoji#66] opened 2016-11-23 07:22 UTC
The emoji keyboard works perfectly yesterday when I started using it in my application except the landscape malfunctioning, but this morning another thing surface, the prompt is now showing above the soft keyboard without modifying anything.

The version used is:
compile 'com.vanniktech:emoji:0.3.0'
compile 'com.vanniktech:emoji:0.4.0

Need help urgently
![screenshot_20161123-080029](https://cloud.githubusercontent.com/assets/11922969/20553562/d7dbfd64-b155-11e6-97ce-031807cf9c3a.png)

**Comment by vanniktech** [comment] 2016-12-11 11:42
Dupe of #26

**Closed by vanniktech** 2016-12-11 11:42 UTC
