### ISSUE TITLE
iOS Emojis PNG size

### ISSUE THREAD

**Issue by ricamgar** [vanniktech/Emoji#241] opened 2018-01-17 12:02 UTC
Hi,
analyzing the size of the apk, I realized that half of it (around 4MB) is used by the emojis png's. I was wondering if it would be possible to reduce the size of those to decrease the apk size. If so, I could try to check for a tool to reduce it without losing quality.

![image](https://user-images.githubusercontent.com/927648/35041843-7bc8c4ea-fb86-11e7-9f60-445df4f86655.png)

Thanks!

**Comment by vanniktech** [comment] 2018-01-17 16:04
Dupe of #88

**Closed by vanniktech** 2018-01-17 16:04 UTC
