### ISSUE TITLE
may be you can make icon pack smaller

### ISSUE THREAD

**Issue by freeparty** [vanniktech/Emoji#126] opened 2017-05-29 17:18 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment] 2017-05-29 18:12
Dupe of #88. 

Feel free to help

**Closed by vanniktech** 2017-05-29 18:12 UTC
