### ISSUE TITLE
Failed to resolve: com.vanniktech:emoji-ios:0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by MattCorte** [vanniktech/Emoji#177] opened 2017-07-17 12:43 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment] 2017-07-17 12:44
Dupe of #176. either use `0.5.0` or add the maven snapshot url.

**Closed by vanniktech** 2017-07-17 12:44 UTC
