### ISSUE TITLE
Keyboard Gesture Buttons Are Covering EmojiPopups

### ISSUE THREAD

**Issue by keidowisu** [vanniktech/Emoji#692] opened 2022-05-02 04:07 UTC
I would like to suggest putting extra padding for bottom navigation bar since it makes touching the bottom line of emojis kinda difficult.

- Version of the library: 0.9.0
- Affected devices: Android 10+ Devices that supports gesture mode
- Affected versions: 10 (Q)

Screenshot(s) showing the issue and reproduction steps are appreciated.

-------------------------------------------
![Screenshot](https://user-images.githubusercontent.com/65654645/166183011-36a1c9ba-a981-4376-95e7-a9af9a369ebe.jpeg)
---------------------------

**Comment by vanniktech** [comment] 2022-05-04 08:38
Duplicate of https://github.com/vanniktech/Emoji/issues/538

Do you have a solution in mind @keidowisu ?

I've already tried finding something but could not find anything :/

**Closed by vanniktech** 2022-05-04 08:38 UTC
