### ISSUE TITLE
emojis cover keyboard 

### ISSUE THREAD

**Issue by martipello** [vanniktech/Emoji#285] opened 2018-06-08 19:04 UTC
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: implementation 'com.vanniktech:emoji-google:0.5.1'
- Affected devices: lg v30 and im guessing other 18:9 style devices
- Affected versions: 8.0 that i know of
![screenshot_2018-06-08-19-23-54](https://user-images.githubusercontent.com/12631051/41176004-d6e6cd28-6b56-11e8-8f09-053968fe6fe9.png)

this is an lg v30 running android 8.0 its an 18:9 (ish) aspect ratio with google keyboard (gboard) and the emoji keyboard is higher than the actual keyboard 
![screenshot_2018-06-08-19-24-01](https://user-images.githubusercontent.com/12631051/41176049-05a47250-6b57-11e8-9384-388fcb824b85.png)

i also have a htc one x on 4.2.2 also with gboard and it is working just fine 16:9 aspect ratio

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment] 2018-06-16 18:32
Dupe of #191

**Closed by vanniktech** 2018-06-16 18:32 UTC

**Comment by martipello** [comment] 2018-06-16 18:41
I've read through 191 and this has not a duplicate I have only the one keyboard showing, it is simply taller than the standard keyboard while using gboard
