### ISSUE TITLE
Am I the only one noticing a slight decrease in quality?

### ISSUE THREAD

**Issue by daniele-athome** [vanniktech/Emoji#356] opened 2019-04-17 19:50 UTC
I've upgraded to 0.6.0 and noticed a decrease in image quality of the emojis. I know it's small, but it's noticeable. Maybe it's because of borders, shadows, I don't know...

Here is from commit 182e1ff4f4:
![Screenshot_1555530212](https://user-images.githubusercontent.com/3763726/56316285-2fe50580-615a-11e9-925b-1edb25233e7c.png)

Here is from 0.6.0:
![Screenshot_1555530002](https://user-images.githubusercontent.com/3763726/56316264-252a7080-615a-11e9-9eba-d826c521b6ad.png)

Maybe something went wrong with sprites generation?

**Comment by rubengees** [comment] 2019-04-17 20:08
Hmm, we have once regenareted the images in the commit https://github.com/vanniktech/Emoji/commit/985af973137a8224c1a945f22fa6d33b6d1b118e.

It also updated the datasource from where we are pulling, maybe that is the cause?

**Comment by daniele-athome** [comment] 2019-04-17 20:40
> It also updated the datasource from where we are pulling, maybe that is the cause?

I don't know... their latest release featuring EmojiOne (4.0.4) shows perfectly shaped emojis, at least for EmojiOne which I'm using now (I know they've been removed, but still...):

https://github.com/iamcal/emoji-data/raw/a97b2d2efa64535d6300660eb2cd15ecb584e79e/sheet_emojione_64.png

Anyway... other emoji sets seems to not be affected by this issue. So, since EmojiOne was removed... I guess I have to close this. :-(

**Comment by rubengees** [comment] 2019-04-17 20:44
We are using `4.1.0` in version `0.6.0` I think.

**Comment by daniele-athome** [comment] 2019-04-17 20:48
> We are using 4.1.0 in version 0.6.0 I think.

Wasn't EmojiOne removed already in 4.1.0?

**Comment by rubengees** [comment] 2019-04-17 22:24
You are right! What I said was wrong, release 0.6.0 did use version 4.0.4. We can try to regenerate with the latest version and see how the quality is of that.

**Comment by daniele-athome** [comment] 2019-04-17 22:33
Already tried with both optimization on and off. No difference.
And the latest version doesn't have EmojiOne anyway...

I switched to iOS emojis now, which are the only ones really fine (graphic quality speaking); Google and Twitter seem somewhat blurry compared to the datasource. Maybe an investigation for those is due.

**Comment by rubengees** [comment] 2019-04-17 22:41
I see, we need to look into that then. Can't think of anything right now what causes that.
I'll reopen the issue to keep track of this.

**Comment by nosikuminyoi** [comment] 2019-07-14 10:46
same issue here, ios emojis... please help

**Comment by nosikuminyoi** [comment] 2019-07-14 11:30
@rubengees

**Comment by vanniktech** [comment] 2019-09-10 16:26
I'll cut a new release soon. Do you want this to be part of @rubengees?

**Comment by rubengees** [comment] 2019-09-11 17:45
I'd love to, but not sure how to proceed here. Our data source has not been updated properly, so we can't really update yet (our data sources always become stale :/).

We wait for at least this PR to be merged: https://github.com/iamcal/emoji-data/pull/153

**Comment by vanniktech** [comment] 2019-09-23 09:11
Would it be possible to maintain a fork of this @rubengees ?

I also want to get started with #102 again. It's the thing that annoys me the most. I always rely on the search

**Comment by rubengees** [comment] 2019-09-23 21:21
Would be possible I guess, but I'm not familiar with how the emoji sheets are generated there.
I also think that a mac book is required, since the images are taken from the installed font files.

**Comment by vanniktech** [comment] 2020-01-29 11:05
The PR was merged

**Comment by mario** [comment] 2020-04-09 20:02
So closing this :)

**Closed by mario** 2020-04-09 20:02 UTC
