### ISSUE TITLE
Incorrect heart emoji detection in EmojiUtils

### ISSUE THREAD

**Issue by vellrya** [vanniktech/Emoji#484] opened 2020-12-17 20:28 UTC
- Version of the library: 0.7.0
- Affected devices: OnePlus 3
- Affected versions: Android 8.0

----------------------------------------------------------------------

Hello, some strange behaviour:
EmojiUtils.emojisCount("❤") return 0. 
Heart symbol is also ignored in method EmojiUtils.emojis (empty list returned).

Thats all, thank you for time spend on maintaing library :)

**Comment by vanniktech** [comment] 2021-04-20 06:45
Dupe of #485

**Closed by vanniktech** 2021-04-20 06:45 UTC
