### ISSUE TITLE
The memory of the device will grow up and finally crash.

### ISSUE THREAD

**Issue by bagvand** [vanniktech/Emoji#369] opened 2019-07-04 05:00 UTC
Hello
I use the last commit of master for my application.
I build EmojiPopup from onCreate of my fragment.
My fragment will be created and destroyed much time.
Problem: The memory of the device will grow up and finally crash.
The instance of EmojiPopup is not static and does not collect by GC. Why?

**Comment by bagvand** [comment] 2019-07-04 06:36
Problem Solved:
steps:
1- adding below function to EmojiPopup.java
  public void releaseMemory() {
    if (Build.VERSION.SDK_INT < 16) {
      rootView.getViewTreeObserver().removeGlobalOnLayoutListener(onGlobalLayoutListener);
    } else {
      rootView.getViewTreeObserver().removeOnGlobalLayoutListener(onGlobalLayoutListener);
    }
  }
2- calling this function from onDestroyView of fragment.

Please add this method to lib or handle it in some other way.

**Comment by vanniktech** [comment] 2019-07-04 07:52
cc @rubengees what do you think?

**Comment by rubengees** [comment] 2019-07-04 09:02
This looks like a memory leak which is caused by our layout listener for the keyboard. @bagvant could you put together a minimal sample App for reproduction?

**Comment by bagvand** [comment] 2019-07-06 04:25
OnCreate Activity:
LoadFragment(FragmentMain);

Button Click in FragmentMain:
LoadFragment(FragmentWithEditTextSticker); // adding fragment 

FragmentWithEditTextSticker OnViewCreated:
setUpEmojiPopUp()

// we can press back and load FragmentWithEditTextSticker again.
// with this example and loading FragmentWithEditTextSticker multiple time then memory will grow up.

**Comment by scalajay** [comment] 2019-07-12 21:16
Hi all, can we get a new version release? I am really looking forward to some of the merged changes.
Thank you.

**Comment by rubengees** [comment] 2019-07-13 15:32
@bagvand Thanks, I am able to reproduce.

**Closed** 2019-07-14 10:06 UTC
Labels: bug
